### ISSUE TITLE
Hack Nerd Font

### ISSUE THREAD

**Issue by swrobel** [gaplo917/Ligatured-Hack#1]
Would it be possible to add a ligaturized version of the Hack [Nerd Font](https://github.com/ryanoasis/nerd-fonts)?

**Comment by gaplo917** [comment]
@swrobel Will take into consideration. 

The actual use case would be used in online not in IDE?

**Comment by swrobel** [comment]
In a terminal emulator

**Comment by rexkyng** [comment]
Any updates on this ?
Would really like to use hack with nerd font and ligatures.

**Comment by gaplo917** [comment]
@swrobel @timescam 🎉 Added Nerd font. Please check the latest release to obtain the ligatured version.
