### ISSUE TITLE
Help regarding a custom build

### ISSUE THREAD

**Issue by Kenneth-Mata** [gaplo917/Ligatured-Hack#10]
I forked the repo and i'm trying to use a docker image to build, the docker image successfully builds, but in running them i get ``Error: pattern 'fonts/scheme/scheme-regular.ttf' didn't match any files.``

i have this in build.py 

```python
tasks = [
    {
        'input': 'fonts/scheme/scheme-regular.ttf',
        'ligatures': [
            'fonts/fira/distr/ttf/FiraCode-Regular.otf',
            'fonts/jetbrainsmono/fonts/ttf/JetBrainsMono-Regular.ttf'
        ]
    },
]
```
and the directory is like this 

![2022-10-18_21-33](https://user-images.githubusercontent.com/92641443/196570055-c84a69c2-040a-4b14-bb86-d84a2ac17b75.png)

**Comment by gaplo917** [comment]
Please add ignore pattern whitelist rule in the `.dockerignore`.

Root Cause: The docker context ignored your fonts and didn't copy to build context.

**Comment by Kenneth-Mata** [comment]
Worked, thanks!
