### ISSUE TITLE
Latest release missing many Fira Code ligatures

### ISSUE THREAD

**Issue by swrobel** [gaplo917/Ligatured-Hack#3]
HackLigatured-v3.003+FC5.2+JBMv1.0.6
macOS 10.14.6
Tested in both VSCode & Atom

Showing the Fira showcase (I've tested both the CCG & regular versions, and they are the same):
<img width="318" alt="Screen Shot 2020-06-16 at 7 40 47 AM" src="https://user-images.githubusercontent.com/157270/84789376-049bb780-afa5-11ea-9874-4681075ba500.png">

Stock Fira Code  5.2:
<img width="335" alt="Screen Shot 2020-06-16 at 7 44 00 AM" src="https://user-images.githubusercontent.com/157270/84789563-3745b000-afa5-11ea-8cf2-01e202b78676.png">

Compare vs latest JBM:
<img width="330" alt="Screen Shot 2020-06-16 at 7 41 09 AM" src="https://user-images.githubusercontent.com/157270/84789356-ff3e6d00-afa4-11ea-9602-ea2e36ed66e2.png">

**Comment by gaplo917** [comment]
@swrobel Thanks for reporting!

**Comment by gaplo917** [comment]
After some investigations, I checked that `.ttf` -> `.otf` conversion is okays.

Seems like FIRA Code v5 changed the way(standard?) to add the ligatures. That's why a portion of ligatures are affected.

Need more time to see how to fix.

**Comment by gaplo917** [comment]
@swrobel 
According to [the comment of Fira Code author](https://github.com/tonsky/FiraCode/issues/1100#issuecomment-658741372), Fira code changed the way to add ligatures.

This change added lots of difficulties in extracting ligatures from Fira Code. The fastest way to get the correct Hack font patched with Fira Code is to fallback to Fira Code v3.1.
