### ISSUE TITLE
Duplicate fonts?

### ISSUE THREAD

**Issue by Diaoul** [gaplo917/Ligatured-Hack#8]
In the release file there are fonts named `HackNerdFontFCLigatured` and some fonts are named `HackNFFCLigatured`. Are those duplicates? If not, what are the differences?

Thanks a lot for your work :cake:

**Comment by gaplo917** [comment]
It should be the variants of windows/linux/mac supported by Nerd.

For more accurate information, you can check the Nerd font official github page. 


Ref:
[The regular patched font](https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts/Hack/Regular/complete)

Thanks!

**Comment by Diaoul** [comment]
Thank you

For reference, `Hack Nerd Font` seems to be the name of the default one and `Hack NF` the Windows compatible ones
